name: Build and Push Docker Image

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: overseerr-media-mender
  
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      with:
        version: '1.11.0'

    - name: Initialize Packer
      run: packer init ./packer/image.pkr.hcl

    - name: Build Docker image with Packer
      run: |
        packer build -debug ./packer/image.pkr.hcl
        docker tag overseerr-media-mender:latest ghcr.io/awanaut/overseerr-media-mender:latest
        docker images

    - name: Tag Docker image
      run: |
        IMAGE_ID=$(docker images --format "{{.ID}}" | head -n 1)
        if [ -z "$IMAGE_ID" ]; then
          echo "No Docker image found"
          exit 1
        fi
        echo "Found image ID: $IMAGE_ID"
        docker tag $IMAGE_ID ghcr.io/awanaut/overseerr-media-mender:latest
        echo "Tagged image. Listing images:"
        docker images

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ghcr.io/awanaut/overseerr-media-mender:latest

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +'%Y.%m.%d_%H-%M')"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        release_name: Release ${{ steps.tag.outputs.release_tag }}
        body: |
          Docker image published to GitHub Container Registry:
          ghcr.io/awanaut/overseerr-media-mender:latest
        draft: false
        prerelease: false
