name: Build and Push Docker Image

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: overseerr-media-mender
  
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - uses: actions/checkout@v2
    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      with:
        version: '1.8.0'
    - name: Debug repository contents
      run: |
        echo "Current directory:"
        pwd
        echo "Directory contents:"
        ls -la
        echo "All files (including hidden):"
        find . -maxdepth 3 -type f
        echo "Git status:"
        git status
    - name: Initialize Packer
      run: packer init ./packer/image.pkr.hcl

    - name: Build Docker image with Packer
      run: |
        packer build ./packer/image.pkr.hcl
        docker tag overseerr-media-mender:latest ghcr.io/awanaut/overseerr-media-mender:latest

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ghcr.io/awanaut/overseerr-media-mender:latest

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +'%Y.%m.%d_%H-%M')"

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.release_tag }}
        release_name: Release ${{ steps.tag.outputs.release_tag }}
        body: |
          Docker image published to GitHub Container Registry:
          ghcr.io/awanaut/overseerr-media-mender:latest
        draft: false
        prerelease: false
