name: Build and Push Docker Image

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: overseerr-media-mender
  
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ghcr.io/awanaut/overseerr-media-mender:latest

    # - name: Create GitHub Release
    #   uses: actions/create-release@v1
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #   with:
    #     tag_name: ${{ github.ref }}
    #     release_name: Release ${{ github.ref }}
    #     body: |
    #       Docker image published to GitHub Container Registry:
    #       ${{ steps.meta.outputs.tags }}
    #     draft: false
    #     prerelease: false
