name: Build and Push Docker Image

on:
  push:
  pull_request:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: overseerr-media-mender
  
jobs:
  packer:
    runs-on: ubuntu-latest
    name: Build Image
    steps:
    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      with:
        version: '1.8.0'
    - name: List repository contents
      run: ls -R
    - name: Initialize Packer
      run: packer init ./packer/image.pkr.hcl

    - name: Build Docker image with Packer
      run: packer build ./packer/image.pkr.hcl

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ghcr.io/awanaut/overseerr-media-mender:latest

    - name: Generate release tag
      id: tag
      run: |
        echo "::set-output name=release_tag::$(date +'%Y.%m.%d_%H-%M')"
    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Docker image published to GitHub Container Registry:
          ${{ steps.meta.outputs.tags }}
        draft: false
        prerelease: false
