name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Packer
      uses: hashicorp/setup-packer@main
      with:
        version: '1.8.0'  # Using a more recent version

    - name: Initialize Packer
      run: packer init .

    - name: Build Docker image with Packer
      run: packer build packer.pkr.hcl

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker image
      run: docker push ghcr.io/awanaut/overseerr-media-mender:latest

    - name: Create GitHub Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Docker image published to GitHub Container Registry:
          ${{ steps.meta.outputs.tags }}
        draft: false
        prerelease: false
